### ISSUE TITLE
string.unpack format strings

### ISSUE THREAD

**Issue by cherue** [adrianherrera/kaitai_struct_lua_runtime#2]
While looking through all the runtimes I noticed that the Lua runtime uses format strings that are platform specific (see [Lua 5.3 Reference Manual](https://www.lua.org/manual/5.3/manual.html#6.4.2)). Would it be better to use `i[n]` and `I[n]` instead?

**Comment by GreyCat** [comment]
@adrianherrera might be able to answer if he's still around?

**Comment by cherue** [comment]
While looking into this some more I tried out the new `integers_min_max` test and found errors with the unsigned max u8 ints. So I tried it with explicit byte sizes like `I8`, `I4`, etc. but that resulted in the same errors - I think I found a bug in Lua:

**Edit: It's not a Lua bug, just a limitation. `string.unpack` always returns a signed `lua_Integer`. Even the "J" conversion option which stands for `lua_Unsigned`. Lua does check integers bigger than 8 bytes [to see if they fit](https://www.lua.org/source/5.3/lstrlib.c.html#unpackint) but no such check for exactly 8 bytes.**

- `I[n]` stands for an unsigned integer of size n
- the return value includes the offset after the unpacked data

```
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio

> string.unpack("I4", "\255\255\255\255")
4294967295	5

> string.unpack("I8", "\255\255\255\255\255\255\255\255")
-1	9

> string.unpack("I8", "\255\255\255\255\255\255\255\127")
9223372036854775807	9

> string.unpack("I8", "\255\255\255\255\255\255\255\128")
-9151314442816847873	9
```

I tried figuring out what goes wrong by looking at the [source](https://www.lua.org/source/5.3/lstrlib.c.html#unpackint) but I'm not fluent in C. My guess is that it has something to do with `lua_Integer`.

Also I now think it would be better to use explicit integer sizes, the result is the same and would be the same on all platforms with all compilers (it currently relies on `short`, `int` and `long`, see [lstrlib.c getoption](https://www.lua.org/source/5.3/lstrlib.c.html#getoption)).

**Comment by adrianherrera** [comment]
Any reason why this was closed?

**Comment by GreyCat** [comment]
@adrianherrera @cherue Proposed a fix in https://github.com/kaitai-io/kaitai_struct_lua_runtime/pull/3 and a pretty exhaustive explanation, while I liked, so I went ahead and merged it.

If you think that's not correct — please feel free to reopen and we can continue discussion.
